name: golden_tests_review
description: A new Flutter project.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  coffee_recipes_module:
    path: modules/coffee_recipes_module
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_svg: ^2.0.5
  get_it: ^7.6.0
  injectable: ^2.1.0
  intl: ^0.18.1
  intl_utils: ^2.8.2

dev_dependencies: 
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.5

flutter_gen:
  enabled: true
  outputs:
    package_parameter_enabled: false
    style: dot-delimiter
  line_length: 80

  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
    lottie: false

  fonts:
    enabled: true

  colors:
    enabled: true
    inputs:
      - assets/colors/colors.xml

flutter_intl:
  enabled: true

flutter:
  uses-material-design: true
  # generate: true # For intl
  assets:
    - assets/
    - assets/colors/
    - assets/icons/

  fonts:
  - family: Poppins Medium
    fonts:
    - asset: assets/fonts/Poppins-Medium.ttf
  - family: Poppins Regular
    fonts:
      - asset: assets/fonts/Poppins-Regular.ttf
  - family: Poppins SemiBold
    fonts:
      - asset: assets/fonts/Poppins-SemiBold.ttf
  - family: Poppins Bold
    fonts:
      - asset: assets/fonts/Poppins-Bold.ttf